### ISSUE TITLE
Online Application Form for FOI Requests

### ISSUE THREAD

**Issue by bcdevex** [bcgov/foi-requests#1]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-online-application-form-for-foi-requests">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-online-application-form-for-foi-requests">visit the opportunity page</a>. The opportunity closes on <b>Friday, February 1, 2019</b>.</p>

**Comment by MatthewPMorris** [comment]
Hello

I'm Matthew the technical contact for this opportunity. Please let me know if you have any questions.

**Comment by chadhosk** [comment]
Hi there, my name is Chad Hoskins and I am the business lead for this project.  Let me know if you have any questions. Thanks!

**Comment by mcousine** [comment]
Hi is it mandatory to do angular css ? Would Microsoft PowerApps integrated with Microsoft flow would do the job plus data hosting in common database service ?
All hosted in a baas plateform integrated with office 365?

Do you have office 365 ?

https://docs.microsoft.com/en-us/powerapps/administrator/create-database

https://docs.microsoft.com/en-us/powerapps/powerapps-overview

https://docs.microsoft.com/en-us/powerapps/user/use-flows

**Comment by mark-a-wilson** [comment]
Hello all interested applicants. Please note that the **closing deadline** for proposals to be received is **Thursday, Jan 31**  at **4:00 PM PST** (as stated on the [opportunity page](https://bcdevexchange.org/opportunities/cwu/opp-online-application-form-for-foi-requests)), _NOT_ Feb 1 as stated at the beginning of this thread. (Bug with the BCDX app) Apologies! 😬 🙏

**Comment by JanetMajocha** [comment]
I am trying to propose a subcontractor who works for our company.  If I enter his name on the Developer page as "the person who is proposing to do the work" I get an "Error: email already exists"  and it changes the contact information in our company profile.  What do you suggest?

**Comment by mark-a-wilson** [comment]
@JanetMajocha - sorry about that - some situations we haven't anticipated and designed for yet! Please try this and let me know if you still have trouble submitting the proposal:

**Developer** tab:
- Check the "Payment can be made to a company" box
- Fill in the name fields for the developer, but delete the email address so it is blank

**Company** tab:
- Fill all of these fields; use your email address, not his.

**Comment by mark-a-wilson** [comment]
Hello anyone who is trying to apply on this opportunity but not able to get over the problem described above. If this is the case, please put the content of your proposal into an email or document and send it to Matthew.Morris@gov.bc.ca by the deadline this afternoon (4:00 pm Pacific Time). We will ensure your proposal is considered.

**Comment by mustafashakeel** [comment]
I was wondering what is the backend language is in and do we use tools like Swagger for API management

**Comment by MatthewPMorris** [comment]
The intention is for the form to only allow you to submit a single FOI request at a time. We wouldn't it to allow multiple FOI requests to be submitted at once. I believe it should be a radio button.

**Comment by mark-a-wilson** [comment]
Hello all, thank you for the overwhelming response -- there were **24** proposals received 😬. I am not involved in the evaluation, but @MatthewPMorris will post shortly to give an update when  evaluations will be completed and an assignee announced. Thanks again for your interest!

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by JanetMajocha** [comment]
Who has it been assigned to?

**Comment by mark-a-wilson** [comment]
@JanetMajocha , @sirturtletheknight and everyone else who applied... the opportunity was assigned to @4umfreak. If you would like feedback on your proposal, please contact Matthew.Morris@gov.bc.ca.
