### ISSUE TITLE
Date format change request

### ISSUE THREAD

**Issue by Brandscaping** [bcgov/foi-requests#4]
Hey Mark and team - are you able to make this change for the IOA team?

Small ask for a tweak on the current form. I’ve noticed that the way it’s designed is that the date is coming out in the following format: dd/mm/yyyy

This is totally reasonable, normally – but unfortunately this does not line up with our tracking software, which uses mm/dd/yyyy

**Comment by 4umfreak** [comment]
Hi Jason, this has been committed to the dev branch as of Aug 13th. I will be leaving it with Matthew to move it into Test.

**Comment by Brandscaping** [comment]
Fantastic, thanks Mark
